server:
  port: ${PORT:8090}

### dependency configuration
auth.provider.service.client.baseUrl: ${S2S_URL:http://127.0.0.1:4502}
idam.s2s-auth.totp_secret: ${IA_S2S_SECRET:AAAAAAAAAAAAAAAC}
idam.s2s-auth.microservice: ${IA_S2S_MICROSERVICE:iac}
idam.s2s-auth.url: ${S2S_URL:http://127.0.0.1:4502}
